// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoRelUHxmciealrExDyPgK-ss_ceoqp0A',
    appId: '1:43173661373:web:1a60047f824a2ac54905d4',
    messagingSenderId: '43173661373',
    projectId: 'discrete-math-4ee58',
    authDomain: 'discrete-math-4ee58.firebaseapp.com',
    storageBucket: 'discrete-math-4ee58.firebasestorage.app',
    measurementId: 'G-WS8BSW2RC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR_jGzWtNGefPTKbSyRzjoefIPqNlsvd0',
    appId: '1:43173661373:android:70d708971e24ecfa4905d4',
    messagingSenderId: '43173661373',
    projectId: 'discrete-math-4ee58',
    storageBucket: 'discrete-math-4ee58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7u-89DHFLvddVYPpBcirjDANaXy5PYgE',
    appId: '1:43173661373:ios:7251e58773e95c4b4905d4',
    messagingSenderId: '43173661373',
    projectId: 'discrete-math-4ee58',
    storageBucket: 'discrete-math-4ee58.firebasestorage.app',
    iosBundleId: 'com.example.discreteMath',
  );
}
